// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	 protoc-gen-go 1.3.5
// 	 protoc 	   v3.6.1
// source: api/user/user.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Salt                 string   `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Roles                []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	OperatorId           int64    `protobuf:"varint,6,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *CreateUserRequest) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *CreateUserRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type CreateUserReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{1}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

func (m *CreateUserReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateUserReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateUserReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UpdateUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Roles                []string `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	OperatorId           int64    `protobuf:"varint,7,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{2}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *UpdateUserRequest) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *UpdateUserRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type UpdateUserReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserReply) Reset()         { *m = UpdateUserReply{} }
func (m *UpdateUserReply) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReply) ProtoMessage()    {}
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{3}
}

func (m *UpdateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReply.Unmarshal(m, b)
}
func (m *UpdateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReply.Marshal(b, m, deterministic)
}
func (m *UpdateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReply.Merge(m, src)
}
func (m *UpdateUserReply) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReply.Size(m)
}
func (m *UpdateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReply proto.InternalMessageInfo

func (m *UpdateUserReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateUserReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId           int64    `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{4}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteUserRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type DeleteUserReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReply) Reset()         { *m = DeleteUserReply{} }
func (m *DeleteUserReply) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReply) ProtoMessage()    {}
func (*DeleteUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{5}
}

func (m *DeleteUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReply.Unmarshal(m, b)
}
func (m *DeleteUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReply.Marshal(b, m, deterministic)
}
func (m *DeleteUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReply.Merge(m, src)
}
func (m *DeleteUserReply) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReply.Size(m)
}
func (m *DeleteUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReply proto.InternalMessageInfo

func (m *DeleteUserReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteUserReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId           int64    `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{6}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type GetUserReply struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               int32     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string    `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserReply) Reset()         { *m = GetUserReply{} }
func (m *GetUserReply) String() string { return proto.CompactTextString(m) }
func (*GetUserReply) ProtoMessage()    {}
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{7}
}

func (m *GetUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReply.Unmarshal(m, b)
}
func (m *GetUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReply.Marshal(b, m, deterministic)
}
func (m *GetUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReply.Merge(m, src)
}
func (m *GetUserReply) XXX_Size() int {
	return xxx_messageInfo_GetUserReply.Size(m)
}
func (m *GetUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReply proto.InternalMessageInfo

func (m *GetUserReply) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUserReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ListUserRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	OperatorId           int64    `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{8}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

func (m *ListUserRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListUserRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListUserRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type ListUserReply struct {
	Users                []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Status               int32       `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string      `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Total                int64       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListUserReply) Reset()         { *m = ListUserReply{} }
func (m *ListUserReply) String() string { return proto.CompactTextString(m) }
func (*ListUserReply) ProtoMessage()    {}
func (*ListUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{9}
}

func (m *ListUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserReply.Unmarshal(m, b)
}
func (m *ListUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserReply.Marshal(b, m, deterministic)
}
func (m *ListUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserReply.Merge(m, src)
}
func (m *ListUserReply) XXX_Size() int {
	return xxx_messageInfo_ListUserReply.Size(m)
}
func (m *ListUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserReply proto.InternalMessageInfo

func (m *ListUserReply) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUserReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListUserReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListUserReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UserInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Salt                 string   `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Role                 []string `protobuf:"bytes,5,rep,name=role,proto3" json:"role,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bc452c1a8bd0aa8, []int{10}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *UserInfo) GetRole() []string {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *UserInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserInfo) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "api.user.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "api.user.CreateUserReply")
	proto.RegisterType((*UpdateUserRequest)(nil), "api.user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserReply)(nil), "api.user.UpdateUserReply")
	proto.RegisterType((*DeleteUserRequest)(nil), "api.user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserReply)(nil), "api.user.DeleteUserReply")
	proto.RegisterType((*GetUserRequest)(nil), "api.user.GetUserRequest")
	proto.RegisterType((*GetUserReply)(nil), "api.user.GetUserReply")
	proto.RegisterType((*ListUserRequest)(nil), "api.user.ListUserRequest")
	proto.RegisterType((*ListUserReply)(nil), "api.user.ListUserReply")
	proto.RegisterType((*UserInfo)(nil), "api.user.UserInfo")
}

func init() {
	proto.RegisterFile("api/user/user.proto", fileDescriptor_3bc452c1a8bd0aa8)
}

var fileDescriptor_3bc452c1a8bd0aa8 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x7f, 0xeb, 0x4c, 0xa1, 0x21, 0x4b, 0x15, 0x4c, 0x10, 0x22, 0xf2, 0x01, 0xe5, 0x94,
	0x4a, 0xe5, 0x18, 0x09, 0x29, 0x60, 0x09, 0x55, 0x70, 0x40, 0x96, 0x7a, 0xe9, 0xa5, 0x2c, 0xf5,
	0x52, 0x59, 0x72, 0x6a, 0xe3, 0xdd, 0x80, 0xc2, 0x33, 0x71, 0xe2, 0x09, 0x78, 0x09, 0xde, 0x07,
	0xcd, 0x7a, 0x9d, 0xdd, 0xda, 0x6e, 0xd4, 0xa8, 0x17, 0x6b, 0x67, 0x67, 0xf2, 0xed, 0x37, 0x5f,
	0xbe, 0xd9, 0x85, 0xa7, 0xb4, 0xcc, 0x4e, 0xd6, 0x9c, 0x55, 0xf2, 0x33, 0x2f, 0xab, 0x42, 0x14,
	0x24, 0xa0, 0x65, 0x36, 0xc7, 0x38, 0xfa, 0x6d, 0xc1, 0xe8, 0x7d, 0xc5, 0xa8, 0x60, 0xe7, 0x9c,
	0x55, 0x09, 0xfb, 0xbe, 0x66, 0x5c, 0x90, 0x09, 0x04, 0x98, 0xbd, 0xa1, 0x2b, 0x16, 0x5a, 0x53,
	0x6b, 0x36, 0x48, 0xb6, 0x31, 0xe6, 0x4a, 0xca, 0xf9, 0xcf, 0xa2, 0x4a, 0x43, 0xbb, 0xce, 0x35,
	0x31, 0x39, 0x06, 0x8f, 0xad, 0x68, 0x96, 0x87, 0x8e, 0x4c, 0xd4, 0x01, 0x21, 0xe0, 0x72, 0x9a,
	0x8b, 0xd0, 0x95, 0x9b, 0x72, 0x8d, 0x95, 0x55, 0x91, 0x33, 0x1e, 0x7a, 0x53, 0x07, 0x2b, 0x65,
	0x40, 0x5e, 0xc1, 0x61, 0x51, 0xb2, 0x8a, 0x8a, 0xa2, 0xba, 0xcc, 0xd2, 0xd0, 0x9f, 0x5a, 0x33,
	0x27, 0x81, 0x66, 0xeb, 0x2c, 0x8d, 0x3e, 0xc2, 0xd0, 0x64, 0x5b, 0xe6, 0x1b, 0x72, 0x04, 0x76,
	0x96, 0x4a, 0x96, 0x4e, 0x62, 0x67, 0x29, 0x19, 0x83, 0xcf, 0x05, 0x15, 0x6b, 0x2e, 0xd9, 0x79,
	0x89, 0x8a, 0xc8, 0x13, 0x70, 0x56, 0xfc, 0x5a, 0x31, 0xc3, 0x65, 0xf4, 0xd7, 0x82, 0xd1, 0x79,
	0x99, 0xb6, 0x7a, 0x6f, 0xe3, 0x99, 0x5a, 0xd8, 0x3b, 0xb4, 0x70, 0xee, 0xd2, 0xc2, 0x35, 0xb5,
	0x18, 0x83, 0x4f, 0xaf, 0x44, 0xf6, 0x83, 0x85, 0xde, 0xd4, 0x9a, 0x05, 0x89, 0x8a, 0xb4, 0x1e,
	0xfe, 0x0e, 0x3d, 0x0e, 0x3a, 0x7a, 0x2c, 0x60, 0x68, 0x76, 0x80, 0x7a, 0xe8, 0xfe, 0xad, 0xbe,
	0xfe, 0x6d, 0xdd, 0x7f, 0x0c, 0xa3, 0x98, 0xe5, 0x6c, 0x77, 0xfb, 0x2d, 0x0a, 0x76, 0x1f, 0x05,
	0x13, 0x65, 0x3f, 0x0a, 0x4b, 0x38, 0xfa, 0xc0, 0xc4, 0x83, 0xce, 0xff, 0x02, 0x8f, 0xb6, 0x10,
	0x78, 0xf8, 0x6b, 0x70, 0xf1, 0xff, 0x91, 0x10, 0x87, 0xa7, 0x64, 0xde, 0x58, 0x7d, 0x8e, 0x25,
	0x67, 0x37, 0xdf, 0x8a, 0x44, 0xe6, 0xf7, 0xf0, 0xc9, 0x05, 0x0c, 0x3f, 0x65, 0xfc, 0x16, 0x4b,
	0x02, 0x6e, 0x49, 0xaf, 0x99, 0xea, 0x4f, 0xae, 0xa5, 0xcd, 0xb3, 0x5f, 0x4c, 0xc1, 0xc9, 0x75,
	0x9b, 0xbd, 0xd3, 0x61, 0xbf, 0x81, 0xc7, 0x1a, 0x1b, 0xe9, 0xcf, 0xc0, 0x43, 0x7a, 0x28, 0x9d,
	0x73, 0x07, 0xff, 0xba, 0xe0, 0xfe, 0x0d, 0xa0, 0xb9, 0x44, 0x21, 0x68, 0x6d, 0x45, 0x27, 0xa9,
	0x83, 0xe8, 0x8f, 0x05, 0x41, 0x83, 0xb9, 0x97, 0xeb, 0xef, 0x3f, 0xe5, 0x04, 0x5c, 0x34, 0xb2,
	0x1a, 0x72, 0xb9, 0x26, 0x2f, 0x01, 0xae, 0xe4, 0x08, 0xa7, 0x97, 0x54, 0xa8, 0x11, 0x1f, 0xa8,
	0x9d, 0xa5, 0xc0, 0xf4, 0x5a, 0x3a, 0x5a, 0xa6, 0x6b, 0xc7, 0x0f, 0xd4, 0xce, 0x52, 0x9c, 0xfe,
	0xb3, 0xc1, 0x45, 0xd2, 0x24, 0x06, 0xd0, 0x37, 0x01, 0x79, 0xa1, 0x65, 0xea, 0xdc, 0x66, 0x93,
	0xe7, 0xfd, 0x49, 0x54, 0x3b, 0x06, 0xd0, 0xf3, 0x63, 0xa2, 0x74, 0xee, 0x05, 0x13, 0xa5, 0x3d,
	0x72, 0x31, 0x80, 0x1e, 0x01, 0x13, 0xa5, 0x33, 0x5e, 0x26, 0x4a, 0x7b, 0x6a, 0x16, 0x70, 0xa0,
	0x8c, 0x4c, 0x42, 0x5d, 0x75, 0x7b, 0x3c, 0x26, 0xe3, 0x9e, 0x0c, 0xfe, 0xf8, 0x2d, 0x04, 0x8d,
	0x8f, 0x88, 0x71, 0x46, 0xcb, 0xb7, 0x93, 0x67, 0x7d, 0xa9, 0x32, 0xdf, 0xbc, 0x8b, 0x60, 0xfb,
	0x26, 0x7c, 0xb6, 0x2e, 0x8e, 0x57, 0x94, 0x0b, 0x56, 0x9d, 0x34, 0x6f, 0xc7, 0x02, 0x3f, 0x5f,
	0x7d, 0xf9, 0x78, 0xbc, 0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x31, 0x8f, 0x0c, 0x13, 0x53, 0x06,
	0x00, 0x00,
}
