// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	 protoc-gen-go 1.3.5
// 	 protoc 	   v3.6.1
// source: api/location/v1/location.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateLocationRequest struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ReferID              int64    `protobuf:"varint,2,opt,name=referID,proto3" json:"referID,omitempty"`
	NodeID               int64    `protobuf:"varint,3,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLocationRequest) Reset()         { *m = CreateLocationRequest{} }
func (m *CreateLocationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLocationRequest) ProtoMessage()    {}
func (*CreateLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c68a9a8211198de7, []int{0}
}

func (m *CreateLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLocationRequest.Unmarshal(m, b)
}
func (m *CreateLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLocationRequest.Marshal(b, m, deterministic)
}
func (m *CreateLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLocationRequest.Merge(m, src)
}
func (m *CreateLocationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLocationRequest.Size(m)
}
func (m *CreateLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLocationRequest proto.InternalMessageInfo

func (m *CreateLocationRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateLocationRequest) GetReferID() int64 {
	if m != nil {
		return m.ReferID
	}
	return 0
}

func (m *CreateLocationRequest) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

type CreateLocationReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLocationReply) Reset()         { *m = CreateLocationReply{} }
func (m *CreateLocationReply) String() string { return proto.CompactTextString(m) }
func (*CreateLocationReply) ProtoMessage()    {}
func (*CreateLocationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c68a9a8211198de7, []int{1}
}

func (m *CreateLocationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLocationReply.Unmarshal(m, b)
}
func (m *CreateLocationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLocationReply.Marshal(b, m, deterministic)
}
func (m *CreateLocationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLocationReply.Merge(m, src)
}
func (m *CreateLocationReply) XXX_Size() int {
	return xxx_messageInfo_CreateLocationReply.Size(m)
}
func (m *CreateLocationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLocationReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLocationReply proto.InternalMessageInfo

func (m *CreateLocationReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateLocationReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteLocationRequest struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ReferID              int64    `protobuf:"varint,2,opt,name=referID,proto3" json:"referID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLocationRequest) Reset()         { *m = DeleteLocationRequest{} }
func (m *DeleteLocationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLocationRequest) ProtoMessage()    {}
func (*DeleteLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c68a9a8211198de7, []int{2}
}

func (m *DeleteLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLocationRequest.Unmarshal(m, b)
}
func (m *DeleteLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLocationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLocationRequest.Merge(m, src)
}
func (m *DeleteLocationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLocationRequest.Size(m)
}
func (m *DeleteLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLocationRequest proto.InternalMessageInfo

func (m *DeleteLocationRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DeleteLocationRequest) GetReferID() int64 {
	if m != nil {
		return m.ReferID
	}
	return 0
}

type DeleteLocationReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLocationReply) Reset()         { *m = DeleteLocationReply{} }
func (m *DeleteLocationReply) String() string { return proto.CompactTextString(m) }
func (*DeleteLocationReply) ProtoMessage()    {}
func (*DeleteLocationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c68a9a8211198de7, []int{3}
}

func (m *DeleteLocationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLocationReply.Unmarshal(m, b)
}
func (m *DeleteLocationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLocationReply.Marshal(b, m, deterministic)
}
func (m *DeleteLocationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLocationReply.Merge(m, src)
}
func (m *DeleteLocationReply) XXX_Size() int {
	return xxx_messageInfo_DeleteLocationReply.Size(m)
}
func (m *DeleteLocationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLocationReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLocationReply proto.InternalMessageInfo

func (m *DeleteLocationReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteLocationReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ListLocationRequest struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ReferID              int64    `protobuf:"varint,2,opt,name=referID,proto3" json:"referID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLocationRequest) Reset()         { *m = ListLocationRequest{} }
func (m *ListLocationRequest) String() string { return proto.CompactTextString(m) }
func (*ListLocationRequest) ProtoMessage()    {}
func (*ListLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c68a9a8211198de7, []int{4}
}

func (m *ListLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocationRequest.Unmarshal(m, b)
}
func (m *ListLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocationRequest.Marshal(b, m, deterministic)
}
func (m *ListLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocationRequest.Merge(m, src)
}
func (m *ListLocationRequest) XXX_Size() int {
	return xxx_messageInfo_ListLocationRequest.Size(m)
}
func (m *ListLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocationRequest proto.InternalMessageInfo

func (m *ListLocationRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ListLocationRequest) GetReferID() int64 {
	if m != nil {
		return m.ReferID
	}
	return 0
}

type ListLocationReply struct {
	Locations            []*LocationInfo `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	Status               int32           `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string          `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListLocationReply) Reset()         { *m = ListLocationReply{} }
func (m *ListLocationReply) String() string { return proto.CompactTextString(m) }
func (*ListLocationReply) ProtoMessage()    {}
func (*ListLocationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c68a9a8211198de7, []int{5}
}

func (m *ListLocationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocationReply.Unmarshal(m, b)
}
func (m *ListLocationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocationReply.Marshal(b, m, deterministic)
}
func (m *ListLocationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocationReply.Merge(m, src)
}
func (m *ListLocationReply) XXX_Size() int {
	return xxx_messageInfo_ListLocationReply.Size(m)
}
func (m *ListLocationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocationReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocationReply proto.InternalMessageInfo

func (m *ListLocationReply) GetLocations() []*LocationInfo {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *ListLocationReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListLocationReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LocationInfo struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ReferID              int64    `protobuf:"varint,2,opt,name=referID,proto3" json:"referID,omitempty"`
	NodeID               int64    `protobuf:"varint,3,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationInfo) Reset()         { *m = LocationInfo{} }
func (m *LocationInfo) String() string { return proto.CompactTextString(m) }
func (*LocationInfo) ProtoMessage()    {}
func (*LocationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c68a9a8211198de7, []int{6}
}

func (m *LocationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationInfo.Unmarshal(m, b)
}
func (m *LocationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationInfo.Marshal(b, m, deterministic)
}
func (m *LocationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationInfo.Merge(m, src)
}
func (m *LocationInfo) XXX_Size() int {
	return xxx_messageInfo_LocationInfo.Size(m)
}
func (m *LocationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LocationInfo proto.InternalMessageInfo

func (m *LocationInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LocationInfo) GetReferID() int64 {
	if m != nil {
		return m.ReferID
	}
	return 0
}

func (m *LocationInfo) GetNodeID() int64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *LocationInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateLocationRequest)(nil), "api.location.v1.CreateLocationRequest")
	proto.RegisterType((*CreateLocationReply)(nil), "api.location.v1.CreateLocationReply")
	proto.RegisterType((*DeleteLocationRequest)(nil), "api.location.v1.DeleteLocationRequest")
	proto.RegisterType((*DeleteLocationReply)(nil), "api.location.v1.DeleteLocationReply")
	proto.RegisterType((*ListLocationRequest)(nil), "api.location.v1.ListLocationRequest")
	proto.RegisterType((*ListLocationReply)(nil), "api.location.v1.ListLocationReply")
	proto.RegisterType((*LocationInfo)(nil), "api.location.v1.LocationInfo")
}

func init() {
	proto.RegisterFile("api/location/v1/location.proto", fileDescriptor_c68a9a8211198de7)
}

var fileDescriptor_c68a9a8211198de7 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x49, 0xd3, 0xaf, 0x9f, 0x1d, 0x4b, 0xd5, 0x2d, 0x95, 0x58, 0x50, 0x4a, 0x10, 0xe9,
	0x29, 0xa5, 0xf5, 0xd8, 0x83, 0x60, 0xe3, 0x21, 0xd0, 0x83, 0xe4, 0x24, 0x82, 0x85, 0x55, 0xb7,
	0x1a, 0x48, 0xb3, 0xeb, 0xee, 0x36, 0x10, 0x7f, 0x8f, 0x3f, 0x54, 0x36, 0x26, 0x6d, 0x92, 0x2e,
	0x14, 0xa9, 0xb7, 0x99, 0xcd, 0xec, 0x93, 0x77, 0x76, 0xde, 0x81, 0x0b, 0xcc, 0x82, 0x61, 0x48,
	0x5f, 0xb0, 0x0c, 0x68, 0x34, 0x8c, 0x47, 0xeb, 0xd8, 0x61, 0x9c, 0x4a, 0x8a, 0x8e, 0x30, 0x0b,
	0x9c, 0xf5, 0x59, 0x3c, 0xb2, 0x9f, 0xa0, 0x3b, 0xe5, 0x04, 0x4b, 0x32, 0xcb, 0x0e, 0x7d, 0xf2,
	0xb1, 0x22, 0x42, 0x22, 0x04, 0x75, 0x99, 0x30, 0x62, 0x19, 0x7d, 0x63, 0xf0, 0xcf, 0x4f, 0x63,
	0x64, 0xc1, 0x7f, 0x4e, 0x16, 0x84, 0x7b, 0xae, 0x55, 0xeb, 0x1b, 0x03, 0xd3, 0xcf, 0x53, 0x74,
	0x0a, 0x8d, 0x88, 0xbe, 0x12, 0xcf, 0xb5, 0xcc, 0xf4, 0x43, 0x96, 0xd9, 0x37, 0xd0, 0xa9, 0xe2,
	0x59, 0x98, 0xa8, 0x72, 0x21, 0xb1, 0x5c, 0x89, 0x0c, 0x9f, 0x65, 0xe8, 0x18, 0xcc, 0xa5, 0x78,
	0x4b, 0xe1, 0x4d, 0x5f, 0x85, 0xf6, 0x1d, 0x74, 0x5d, 0x12, 0x92, 0x3d, 0xf5, 0x29, 0x1d, 0x55,
	0xcc, 0xef, 0x74, 0x4c, 0xa1, 0x33, 0x0b, 0x84, 0xdc, 0x4f, 0xc5, 0x27, 0x9c, 0x94, 0x21, 0x4a,
	0xc3, 0x04, 0x9a, 0xf9, 0x40, 0x94, 0x0c, 0x73, 0x70, 0x38, 0x3e, 0x77, 0x2a, 0x63, 0x72, 0xf2,
	0x2b, 0x5e, 0xb4, 0xa0, 0xfe, 0xa6, 0xbe, 0xd0, 0x40, 0x4d, 0xd7, 0x80, 0xb9, 0x69, 0xe0, 0x1d,
	0x5a, 0x45, 0xc8, 0xdf, 0xcc, 0x57, 0x51, 0x18, 0xe5, 0xd2, 0xaa, 0xff, 0x50, 0x54, 0x3c, 0xfe,
	0xaa, 0xc1, 0x41, 0xfe, 0x2b, 0x34, 0x87, 0x76, 0xd9, 0x00, 0xe8, 0x6a, 0xab, 0x39, 0xad, 0x01,
	0x7b, 0x97, 0x3b, 0xeb, 0xd4, 0xeb, 0xcd, 0xa1, 0x5d, 0x1e, 0xac, 0x86, 0xaf, 0x35, 0x90, 0x86,
	0xaf, 0x73, 0xc8, 0x03, 0xb4, 0x8a, 0x23, 0x43, 0xdb, 0xb7, 0x34, 0xb6, 0xe8, 0xd9, 0x3b, 0xaa,
	0x58, 0x98, 0xdc, 0x3a, 0x50, 0x5d, 0xc6, 0x7b, 0xe3, 0xf1, 0x6c, 0x89, 0x85, 0x24, 0x7c, 0x58,
	0x59, 0xe3, 0x49, 0x3c, 0x7a, 0x6e, 0xa4, 0x1b, 0x7c, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0xd3, 0x34, 0x3a, 0xe3, 0x03, 0x00, 0x00,
}
