// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	 protoc-gen-go 1.3.5
// 	 protoc 	   v3.6.1
// source: api/acl/v1/acl.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNKNOWN ResourceType = 0
	ResourceType_RESOURCE_TYPE_BUCKET  ResourceType = 1
	ResourceType_RESOURCE_TYPE_OBJECT  ResourceType = 2
)

var ResourceType_name = map[int32]string{
	0: "RESOURCE_TYPE_UNKNOWN",
	1: "RESOURCE_TYPE_BUCKET",
	2: "RESOURCE_TYPE_OBJECT",
}

var ResourceType_value = map[string]int32{
	"RESOURCE_TYPE_UNKNOWN": 0,
	"RESOURCE_TYPE_BUCKET":  1,
	"RESOURCE_TYPE_OBJECT":  2,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}

func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{0}
}

type CreateAclRequest struct {
	ResourceId           int64    `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType         int32    `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	TargetId             int64    `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType           int32    `protobuf:"varint,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Permission           int32    `protobuf:"varint,5,opt,name=permission,proto3" json:"permission,omitempty"`
	OperatorId           int64    `protobuf:"varint,6,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAclRequest) Reset()         { *m = CreateAclRequest{} }
func (m *CreateAclRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAclRequest) ProtoMessage()    {}
func (*CreateAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{0}
}

func (m *CreateAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAclRequest.Unmarshal(m, b)
}
func (m *CreateAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAclRequest.Marshal(b, m, deterministic)
}
func (m *CreateAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAclRequest.Merge(m, src)
}
func (m *CreateAclRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAclRequest.Size(m)
}
func (m *CreateAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAclRequest proto.InternalMessageInfo

func (m *CreateAclRequest) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *CreateAclRequest) GetResourceType() int32 {
	if m != nil {
		return m.ResourceType
	}
	return 0
}

func (m *CreateAclRequest) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *CreateAclRequest) GetTargetType() int32 {
	if m != nil {
		return m.TargetType
	}
	return 0
}

func (m *CreateAclRequest) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *CreateAclRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type CreateAclReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceId           int64    `protobuf:"varint,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	TargetId             int64    `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType           int32    `protobuf:"varint,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Permission           int32    `protobuf:"varint,5,opt,name=permission,proto3" json:"permission,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,9,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAclReply) Reset()         { *m = CreateAclReply{} }
func (m *CreateAclReply) String() string { return proto.CompactTextString(m) }
func (*CreateAclReply) ProtoMessage()    {}
func (*CreateAclReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{1}
}

func (m *CreateAclReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAclReply.Unmarshal(m, b)
}
func (m *CreateAclReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAclReply.Marshal(b, m, deterministic)
}
func (m *CreateAclReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAclReply.Merge(m, src)
}
func (m *CreateAclReply) XXX_Size() int {
	return xxx_messageInfo_CreateAclReply.Size(m)
}
func (m *CreateAclReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAclReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAclReply proto.InternalMessageInfo

func (m *CreateAclReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateAclReply) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *CreateAclReply) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *CreateAclReply) GetTargetType() int32 {
	if m != nil {
		return m.TargetType
	}
	return 0
}

func (m *CreateAclReply) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *CreateAclReply) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *CreateAclReply) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *CreateAclReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateAclReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UpdateAclRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Permission           int32    `protobuf:"varint,2,opt,name=permission,proto3" json:"permission,omitempty"`
	OperatorId           int64    `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAclRequest) Reset()         { *m = UpdateAclRequest{} }
func (m *UpdateAclRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAclRequest) ProtoMessage()    {}
func (*UpdateAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{2}
}

func (m *UpdateAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAclRequest.Unmarshal(m, b)
}
func (m *UpdateAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAclRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAclRequest.Merge(m, src)
}
func (m *UpdateAclRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAclRequest.Size(m)
}
func (m *UpdateAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAclRequest proto.InternalMessageInfo

func (m *UpdateAclRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAclRequest) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *UpdateAclRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type UpdateAclReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAclReply) Reset()         { *m = UpdateAclReply{} }
func (m *UpdateAclReply) String() string { return proto.CompactTextString(m) }
func (*UpdateAclReply) ProtoMessage()    {}
func (*UpdateAclReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{3}
}

func (m *UpdateAclReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAclReply.Unmarshal(m, b)
}
func (m *UpdateAclReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAclReply.Marshal(b, m, deterministic)
}
func (m *UpdateAclReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAclReply.Merge(m, src)
}
func (m *UpdateAclReply) XXX_Size() int {
	return xxx_messageInfo_UpdateAclReply.Size(m)
}
func (m *UpdateAclReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAclReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAclReply proto.InternalMessageInfo

func (m *UpdateAclReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateAclReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteAclRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId           int64    `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAclRequest) Reset()         { *m = DeleteAclRequest{} }
func (m *DeleteAclRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAclRequest) ProtoMessage()    {}
func (*DeleteAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{4}
}

func (m *DeleteAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAclRequest.Unmarshal(m, b)
}
func (m *DeleteAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAclRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAclRequest.Merge(m, src)
}
func (m *DeleteAclRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAclRequest.Size(m)
}
func (m *DeleteAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAclRequest proto.InternalMessageInfo

func (m *DeleteAclRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteAclRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type DeleteAclReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAclReply) Reset()         { *m = DeleteAclReply{} }
func (m *DeleteAclReply) String() string { return proto.CompactTextString(m) }
func (*DeleteAclReply) ProtoMessage()    {}
func (*DeleteAclReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{5}
}

func (m *DeleteAclReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAclReply.Unmarshal(m, b)
}
func (m *DeleteAclReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAclReply.Marshal(b, m, deterministic)
}
func (m *DeleteAclReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAclReply.Merge(m, src)
}
func (m *DeleteAclReply) XXX_Size() int {
	return xxx_messageInfo_DeleteAclReply.Size(m)
}
func (m *DeleteAclReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAclReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAclReply proto.InternalMessageInfo

func (m *DeleteAclReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteAclReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ListAclRequest struct {
	ResourceId           int64    `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	OperatorId           int64    `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ResourceType         int32    `protobuf:"varint,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAclRequest) Reset()         { *m = ListAclRequest{} }
func (m *ListAclRequest) String() string { return proto.CompactTextString(m) }
func (*ListAclRequest) ProtoMessage()    {}
func (*ListAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{6}
}

func (m *ListAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAclRequest.Unmarshal(m, b)
}
func (m *ListAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAclRequest.Marshal(b, m, deterministic)
}
func (m *ListAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAclRequest.Merge(m, src)
}
func (m *ListAclRequest) XXX_Size() int {
	return xxx_messageInfo_ListAclRequest.Size(m)
}
func (m *ListAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAclRequest proto.InternalMessageInfo

func (m *ListAclRequest) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *ListAclRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *ListAclRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAclRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAclRequest) GetResourceType() int32 {
	if m != nil {
		return m.ResourceType
	}
	return 0
}

type ListAclReply struct {
	AclList              []*AclInfo `protobuf:"bytes,1,rep,name=acl_list,json=aclList,proto3" json:"acl_list,omitempty"`
	Status               int32      `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string     `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Total                int64      `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAclReply) Reset()         { *m = ListAclReply{} }
func (m *ListAclReply) String() string { return proto.CompactTextString(m) }
func (*ListAclReply) ProtoMessage()    {}
func (*ListAclReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{7}
}

func (m *ListAclReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAclReply.Unmarshal(m, b)
}
func (m *ListAclReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAclReply.Marshal(b, m, deterministic)
}
func (m *ListAclReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAclReply.Merge(m, src)
}
func (m *ListAclReply) XXX_Size() int {
	return xxx_messageInfo_ListAclReply.Size(m)
}
func (m *ListAclReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAclReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListAclReply proto.InternalMessageInfo

func (m *ListAclReply) GetAclList() []*AclInfo {
	if m != nil {
		return m.AclList
	}
	return nil
}

func (m *ListAclReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListAclReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListAclReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AclInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceId           int64    `protobuf:"varint,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	TargetId             int64    `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType           int32    `protobuf:"varint,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Permission           int32    `protobuf:"varint,5,opt,name=permission,proto3" json:"permission,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AclInfo) Reset()         { *m = AclInfo{} }
func (m *AclInfo) String() string { return proto.CompactTextString(m) }
func (*AclInfo) ProtoMessage()    {}
func (*AclInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebee72a3d0710e04, []int{8}
}

func (m *AclInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AclInfo.Unmarshal(m, b)
}
func (m *AclInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AclInfo.Marshal(b, m, deterministic)
}
func (m *AclInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AclInfo.Merge(m, src)
}
func (m *AclInfo) XXX_Size() int {
	return xxx_messageInfo_AclInfo.Size(m)
}
func (m *AclInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AclInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AclInfo proto.InternalMessageInfo

func (m *AclInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AclInfo) GetResourceId() int64 {
	if m != nil {
		return m.ResourceId
	}
	return 0
}

func (m *AclInfo) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *AclInfo) GetTargetType() int32 {
	if m != nil {
		return m.TargetType
	}
	return 0
}

func (m *AclInfo) GetPermission() int32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *AclInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AclInfo) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.acl.v1.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterType((*CreateAclRequest)(nil), "api.acl.v1.CreateAclRequest")
	proto.RegisterType((*CreateAclReply)(nil), "api.acl.v1.CreateAclReply")
	proto.RegisterType((*UpdateAclRequest)(nil), "api.acl.v1.UpdateAclRequest")
	proto.RegisterType((*UpdateAclReply)(nil), "api.acl.v1.UpdateAclReply")
	proto.RegisterType((*DeleteAclRequest)(nil), "api.acl.v1.DeleteAclRequest")
	proto.RegisterType((*DeleteAclReply)(nil), "api.acl.v1.DeleteAclReply")
	proto.RegisterType((*ListAclRequest)(nil), "api.acl.v1.ListAclRequest")
	proto.RegisterType((*ListAclReply)(nil), "api.acl.v1.ListAclReply")
	proto.RegisterType((*AclInfo)(nil), "api.acl.v1.AclInfo")
}

func init() {
	proto.RegisterFile("api/acl/v1/acl.proto", fileDescriptor_ebee72a3d0710e04)
}

var fileDescriptor_ebee72a3d0710e04 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0x4f, 0x8f, 0xd2, 0x40,
	0x1c, 0xb5, 0xed, 0xf2, 0xa7, 0xbf, 0x45, 0xd2, 0x8c, 0x68, 0x2a, 0xfe, 0x23, 0xe8, 0x81, 0x78,
	0x80, 0xb0, 0xde, 0xf4, 0x60, 0x00, 0x7b, 0xc0, 0x35, 0xb0, 0xe9, 0x42, 0x8c, 0x26, 0xa6, 0x19,
	0xdb, 0x91, 0x34, 0x29, 0xdb, 0xb1, 0x33, 0x90, 0xb0, 0x07, 0xaf, 0x7e, 0x08, 0xbf, 0x80, 0x9f,
	0x48, 0xbf, 0x8e, 0x99, 0x69, 0x29, 0x6d, 0x41, 0x37, 0x7b, 0xf0, 0xb2, 0xa7, 0x76, 0xde, 0xeb,
	0xbc, 0xbe, 0xdf, 0x6f, 0xe6, 0xcd, 0x40, 0x03, 0x53, 0xbf, 0x87, 0xdd, 0xa0, 0xb7, 0xee, 0x8b,
	0x47, 0x97, 0x46, 0x21, 0x0f, 0x11, 0x60, 0xea, 0x77, 0xc5, 0x70, 0xdd, 0x6f, 0xff, 0x56, 0xc0,
	0x18, 0x45, 0x04, 0x73, 0x32, 0x70, 0x03, 0x9b, 0x7c, 0x5d, 0x11, 0xc6, 0xd1, 0x13, 0x38, 0x8e,
	0x08, 0x0b, 0x57, 0x91, 0x4b, 0x1c, 0xdf, 0x33, 0x95, 0x96, 0xd2, 0xd1, 0x6c, 0xd8, 0x42, 0x63,
	0x0f, 0x3d, 0x85, 0xdb, 0xe9, 0x07, 0x7c, 0x43, 0x89, 0xa9, 0xb6, 0x94, 0x4e, 0xc9, 0xae, 0x6d,
	0xc1, 0xd9, 0x86, 0x12, 0xf4, 0x00, 0x74, 0x8e, 0xa3, 0x05, 0xe1, 0x42, 0x43, 0x93, 0x1a, 0xd5,
	0x18, 0x18, 0x7b, 0xe2, 0x17, 0x09, 0x29, 0xe7, 0x1f, 0xc9, 0xf9, 0x10, 0x43, 0x72, 0xf6, 0x63,
	0x00, 0x4a, 0xa2, 0xa5, 0xcf, 0x98, 0x1f, 0x5e, 0x98, 0xa5, 0x98, 0xdf, 0x21, 0x42, 0x20, 0xa4,
	0x24, 0xc2, 0x3c, 0x8c, 0x84, 0x7e, 0x39, 0xf6, 0xb8, 0x85, 0xc6, 0x5e, 0xfb, 0xbb, 0x0a, 0xf5,
	0x4c, 0x65, 0x34, 0xd8, 0xa0, 0x3a, 0xa8, 0x69, 0x39, 0xaa, 0xef, 0x15, 0xeb, 0x54, 0xf7, 0xea,
	0xfc, 0xbf, 0x25, 0x3c, 0x02, 0x70, 0xa5, 0x41, 0xcf, 0xc1, 0x3c, 0xa9, 0x40, 0x4f, 0x90, 0x01,
	0x17, 0xf4, 0x8a, 0x7a, 0x5b, 0xba, 0x12, 0xd3, 0x09, 0x32, 0xe0, 0xe8, 0x1e, 0x94, 0x19, 0xc7,
	0x7c, 0xc5, 0xcc, 0xaa, 0x54, 0x4e, 0x46, 0xc8, 0x00, 0x6d, 0xc9, 0x16, 0xa6, 0xde, 0x52, 0x3a,
	0xba, 0x2d, 0x5e, 0xdb, 0x2e, 0x18, 0x73, 0x39, 0x2d, 0xb3, 0xc4, 0xc5, 0x56, 0xe4, 0xbd, 0xaa,
	0x57, 0xb5, 0x5b, 0xdb, 0x6b, 0xf7, 0x4b, 0xa8, 0x67, 0x7e, 0x22, 0xba, 0xbd, 0x33, 0xa8, 0x1c,
	0x32, 0xa8, 0xee, 0x0c, 0x8e, 0xc0, 0x78, 0x43, 0x02, 0xf2, 0x4f, 0x83, 0x05, 0x03, 0xea, 0x21,
	0x03, 0x19, 0x91, 0xeb, 0x19, 0xf8, 0xa9, 0x40, 0xfd, 0x9d, 0xcf, 0xf8, 0x75, 0x32, 0x70, 0x95,
	0x21, 0x84, 0xe0, 0x88, 0xe2, 0x05, 0x91, 0xbd, 0x2a, 0xd9, 0xf2, 0x5d, 0x6c, 0x28, 0xf1, 0x74,
	0x98, 0x7f, 0xb9, 0xdd, 0x31, 0x55, 0x01, 0x9c, 0xfb, 0x97, 0x64, 0x3f, 0x55, 0xa5, 0xfd, 0x54,
	0xb5, 0xbf, 0x41, 0x2d, 0x75, 0x2a, 0x8a, 0xec, 0x42, 0x15, 0xbb, 0x81, 0x13, 0xf8, 0x8c, 0x9b,
	0x4a, 0x4b, 0xeb, 0x1c, 0x9f, 0xdc, 0xe9, 0xee, 0xf2, 0xdd, 0x1d, 0xb8, 0xc1, 0xf8, 0xe2, 0x4b,
	0x68, 0x57, 0xb0, 0x1b, 0x88, 0x79, 0x99, 0xa6, 0xa8, 0x87, 0x9a, 0xa2, 0xa5, 0x4d, 0x41, 0x0d,
	0x28, 0xf1, 0x90, 0xe3, 0x40, 0xfa, 0xd4, 0xec, 0x78, 0xd0, 0xfe, 0xa5, 0x40, 0x25, 0x11, 0xbd,
	0x51, 0x79, 0x7a, 0xfe, 0x09, 0x6a, 0x76, 0xf6, 0xf8, 0xba, 0x0f, 0x77, 0x6d, 0xeb, 0x7c, 0x3a,
	0xb7, 0x47, 0x96, 0x33, 0xfb, 0x70, 0x66, 0x39, 0xf3, 0xc9, 0xe9, 0x64, 0xfa, 0x7e, 0x62, 0xdc,
	0x42, 0x26, 0x34, 0xf2, 0xd4, 0x70, 0x3e, 0x3a, 0xb5, 0x66, 0x86, 0xb2, 0xcf, 0x4c, 0x87, 0x6f,
	0xad, 0xd1, 0xcc, 0x50, 0x4f, 0x7e, 0xa8, 0xa0, 0x0d, 0xdc, 0x00, 0x59, 0xa0, 0xa7, 0xa7, 0x12,
	0x7a, 0x98, 0x5d, 0xaa, 0xe2, 0x31, 0xdc, 0x6c, 0xfe, 0x85, 0x15, 0xcb, 0x6e, 0x81, 0x9e, 0xc6,
	0x2d, 0x2f, 0x53, 0x8c, 0x7a, 0x5e, 0xa6, 0x90, 0x51, 0x0b, 0xf4, 0x34, 0x34, 0x79, 0x99, 0x62,
	0x20, 0xf3, 0x32, 0x85, 0xa4, 0xbd, 0x86, 0x4a, 0xb2, 0x29, 0x51, 0xee, 0xb3, 0x7c, 0xa6, 0x9a,
	0xe6, 0x41, 0x8e, 0x06, 0x9b, 0xe1, 0x33, 0xc8, 0x5c, 0x4a, 0x67, 0xca, 0xc7, 0xc6, 0x12, 0x33,
	0x4e, 0xa2, 0xde, 0xee, 0xfe, 0x7a, 0xb5, 0xee, 0x7f, 0x2e, 0xcb, 0xfb, 0xeb, 0xc5, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x21, 0x29, 0xee, 0xd4, 0xd7, 0x06, 0x00, 0x00,
}
