// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: api/acl/v1/acl.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Acl_CreateAcl_FullMethodName = "/api.acl.v1.Acl/CreateAcl"
	Acl_UpdateAcl_FullMethodName = "/api.acl.v1.Acl/UpdateAcl"
	Acl_DeleteAcl_FullMethodName = "/api.acl.v1.Acl/DeleteAcl"
	Acl_ListAcl_FullMethodName   = "/api.acl.v1.Acl/ListAcl"
)

// AclClient is the client API for Acl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AclClient interface {
	CreateAcl(ctx context.Context, in *CreateAclRequest, opts ...grpc.CallOption) (*CreateAclReply, error)
	UpdateAcl(ctx context.Context, in *UpdateAclRequest, opts ...grpc.CallOption) (*UpdateAclReply, error)
	DeleteAcl(ctx context.Context, in *DeleteAclRequest, opts ...grpc.CallOption) (*DeleteAclReply, error)
	ListAcl(ctx context.Context, in *ListAclRequest, opts ...grpc.CallOption) (*ListAclReply, error)
}

type aclClient struct {
	cc grpc.ClientConnInterface
}

func NewAclClient(cc grpc.ClientConnInterface) AclClient {
	return &aclClient{cc}
}

func (c *aclClient) CreateAcl(ctx context.Context, in *CreateAclRequest, opts ...grpc.CallOption) (*CreateAclReply, error) {
	out := new(CreateAclReply)
	err := c.cc.Invoke(ctx, Acl_CreateAcl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclClient) UpdateAcl(ctx context.Context, in *UpdateAclRequest, opts ...grpc.CallOption) (*UpdateAclReply, error) {
	out := new(UpdateAclReply)
	err := c.cc.Invoke(ctx, Acl_UpdateAcl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclClient) DeleteAcl(ctx context.Context, in *DeleteAclRequest, opts ...grpc.CallOption) (*DeleteAclReply, error) {
	out := new(DeleteAclReply)
	err := c.cc.Invoke(ctx, Acl_DeleteAcl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aclClient) ListAcl(ctx context.Context, in *ListAclRequest, opts ...grpc.CallOption) (*ListAclReply, error) {
	out := new(ListAclReply)
	err := c.cc.Invoke(ctx, Acl_ListAcl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AclServer is the server API for Acl service.
// All implementations must embed UnimplementedAclServer
// for forward compatibility
type AclServer interface {
	CreateAcl(context.Context, *CreateAclRequest) (*CreateAclReply, error)
	UpdateAcl(context.Context, *UpdateAclRequest) (*UpdateAclReply, error)
	DeleteAcl(context.Context, *DeleteAclRequest) (*DeleteAclReply, error)
	ListAcl(context.Context, *ListAclRequest) (*ListAclReply, error)
	mustEmbedUnimplementedAclServer()
}

// UnimplementedAclServer must be embedded to have forward compatible implementations.
type UnimplementedAclServer struct {
}

func (UnimplementedAclServer) CreateAcl(context.Context, *CreateAclRequest) (*CreateAclReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAcl not implemented")
}
func (UnimplementedAclServer) UpdateAcl(context.Context, *UpdateAclRequest) (*UpdateAclReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAcl not implemented")
}
func (UnimplementedAclServer) DeleteAcl(context.Context, *DeleteAclRequest) (*DeleteAclReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAcl not implemented")
}
func (UnimplementedAclServer) ListAcl(context.Context, *ListAclRequest) (*ListAclReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAcl not implemented")
}
func (UnimplementedAclServer) mustEmbedUnimplementedAclServer() {}

// UnsafeAclServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AclServer will
// result in compilation errors.
type UnsafeAclServer interface {
	mustEmbedUnimplementedAclServer()
}

func RegisterAclServer(s grpc.ServiceRegistrar, srv AclServer) {
	s.RegisterService(&Acl_ServiceDesc, srv)
}

func _Acl_CreateAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).CreateAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acl_CreateAcl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).CreateAcl(ctx, req.(*CreateAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acl_UpdateAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).UpdateAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acl_UpdateAcl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).UpdateAcl(ctx, req.(*UpdateAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acl_DeleteAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).DeleteAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acl_DeleteAcl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).DeleteAcl(ctx, req.(*DeleteAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acl_ListAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AclServer).ListAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acl_ListAcl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AclServer).ListAcl(ctx, req.(*ListAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Acl_ServiceDesc is the grpc.ServiceDesc for Acl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Acl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.acl.v1.Acl",
	HandlerType: (*AclServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAcl",
			Handler:    _Acl_CreateAcl_Handler,
		},
		{
			MethodName: "UpdateAcl",
			Handler:    _Acl_UpdateAcl_Handler,
		},
		{
			MethodName: "DeleteAcl",
			Handler:    _Acl_DeleteAcl_Handler,
		},
		{
			MethodName: "ListAcl",
			Handler:    _Acl_ListAcl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/acl/v1/acl.proto",
}
