// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	 protoc-gen-go 1.3.5
// 	 protoc 	   v3.6.1
// source: api/bucket/v1/bucket.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBucketRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OwnerID              int64    `protobuf:"varint,3,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketRequest) Reset()         { *m = CreateBucketRequest{} }
func (m *CreateBucketRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBucketRequest) ProtoMessage()    {}
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{0}
}

func (m *CreateBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketRequest.Unmarshal(m, b)
}
func (m *CreateBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketRequest.Marshal(b, m, deterministic)
}
func (m *CreateBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketRequest.Merge(m, src)
}
func (m *CreateBucketRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBucketRequest.Size(m)
}
func (m *CreateBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketRequest proto.InternalMessageInfo

func (m *CreateBucketRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBucketRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateBucketRequest) GetOwnerID() int64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

type CreateBucketReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerID              int64    `protobuf:"varint,4,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketReply) Reset()         { *m = CreateBucketReply{} }
func (m *CreateBucketReply) String() string { return proto.CompactTextString(m) }
func (*CreateBucketReply) ProtoMessage()    {}
func (*CreateBucketReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{1}
}

func (m *CreateBucketReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketReply.Unmarshal(m, b)
}
func (m *CreateBucketReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketReply.Marshal(b, m, deterministic)
}
func (m *CreateBucketReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketReply.Merge(m, src)
}
func (m *CreateBucketReply) XXX_Size() int {
	return xxx_messageInfo_CreateBucketReply.Size(m)
}
func (m *CreateBucketReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketReply proto.InternalMessageInfo

func (m *CreateBucketReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateBucketReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBucketReply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateBucketReply) GetOwnerID() int64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

func (m *CreateBucketReply) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *CreateBucketReply) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *CreateBucketReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateBucketReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UpdateBucketRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OperatorId           int64    `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBucketRequest) Reset()         { *m = UpdateBucketRequest{} }
func (m *UpdateBucketRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBucketRequest) ProtoMessage()    {}
func (*UpdateBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{2}
}

func (m *UpdateBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBucketRequest.Unmarshal(m, b)
}
func (m *UpdateBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBucketRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBucketRequest.Merge(m, src)
}
func (m *UpdateBucketRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBucketRequest.Size(m)
}
func (m *UpdateBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBucketRequest proto.InternalMessageInfo

func (m *UpdateBucketRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateBucketRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateBucketRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateBucketRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type UpdateBucketReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBucketReply) Reset()         { *m = UpdateBucketReply{} }
func (m *UpdateBucketReply) String() string { return proto.CompactTextString(m) }
func (*UpdateBucketReply) ProtoMessage()    {}
func (*UpdateBucketReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{3}
}

func (m *UpdateBucketReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBucketReply.Unmarshal(m, b)
}
func (m *UpdateBucketReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBucketReply.Marshal(b, m, deterministic)
}
func (m *UpdateBucketReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBucketReply.Merge(m, src)
}
func (m *UpdateBucketReply) XXX_Size() int {
	return xxx_messageInfo_UpdateBucketReply.Size(m)
}
func (m *UpdateBucketReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBucketReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBucketReply proto.InternalMessageInfo

func (m *UpdateBucketReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateBucketReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteBucketRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId           int64    `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBucketRequest) Reset()         { *m = DeleteBucketRequest{} }
func (m *DeleteBucketRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBucketRequest) ProtoMessage()    {}
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{4}
}

func (m *DeleteBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBucketRequest.Unmarshal(m, b)
}
func (m *DeleteBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBucketRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBucketRequest.Merge(m, src)
}
func (m *DeleteBucketRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBucketRequest.Size(m)
}
func (m *DeleteBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBucketRequest proto.InternalMessageInfo

func (m *DeleteBucketRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteBucketRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type DeleteBucketReply struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBucketReply) Reset()         { *m = DeleteBucketReply{} }
func (m *DeleteBucketReply) String() string { return proto.CompactTextString(m) }
func (*DeleteBucketReply) ProtoMessage()    {}
func (*DeleteBucketReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{5}
}

func (m *DeleteBucketReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBucketReply.Unmarshal(m, b)
}
func (m *DeleteBucketReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBucketReply.Marshal(b, m, deterministic)
}
func (m *DeleteBucketReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBucketReply.Merge(m, src)
}
func (m *DeleteBucketReply) XXX_Size() int {
	return xxx_messageInfo_DeleteBucketReply.Size(m)
}
func (m *DeleteBucketReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBucketReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBucketReply proto.InternalMessageInfo

func (m *DeleteBucketReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteBucketReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetBucketRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId           int64    `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBucketRequest) Reset()         { *m = GetBucketRequest{} }
func (m *GetBucketRequest) String() string { return proto.CompactTextString(m) }
func (*GetBucketRequest) ProtoMessage()    {}
func (*GetBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{6}
}

func (m *GetBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketRequest.Unmarshal(m, b)
}
func (m *GetBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketRequest.Marshal(b, m, deterministic)
}
func (m *GetBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketRequest.Merge(m, src)
}
func (m *GetBucketRequest) XXX_Size() int {
	return xxx_messageInfo_GetBucketRequest.Size(m)
}
func (m *GetBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketRequest proto.InternalMessageInfo

func (m *GetBucketRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetBucketRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type GetBucketReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerID              int64    `protobuf:"varint,4,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,8,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBucketReply) Reset()         { *m = GetBucketReply{} }
func (m *GetBucketReply) String() string { return proto.CompactTextString(m) }
func (*GetBucketReply) ProtoMessage()    {}
func (*GetBucketReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{7}
}

func (m *GetBucketReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBucketReply.Unmarshal(m, b)
}
func (m *GetBucketReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBucketReply.Marshal(b, m, deterministic)
}
func (m *GetBucketReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBucketReply.Merge(m, src)
}
func (m *GetBucketReply) XXX_Size() int {
	return xxx_messageInfo_GetBucketReply.Size(m)
}
func (m *GetBucketReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBucketReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBucketReply proto.InternalMessageInfo

func (m *GetBucketReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetBucketReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetBucketReply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetBucketReply) GetOwnerID() int64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

func (m *GetBucketReply) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetBucketReply) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *GetBucketReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetBucketReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ListBucketRequest struct {
	OwnerID              int64    `protobuf:"varint,1,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OperatorId           int64    `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBucketRequest) Reset()         { *m = ListBucketRequest{} }
func (m *ListBucketRequest) String() string { return proto.CompactTextString(m) }
func (*ListBucketRequest) ProtoMessage()    {}
func (*ListBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{8}
}

func (m *ListBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketRequest.Unmarshal(m, b)
}
func (m *ListBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketRequest.Marshal(b, m, deterministic)
}
func (m *ListBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketRequest.Merge(m, src)
}
func (m *ListBucketRequest) XXX_Size() int {
	return xxx_messageInfo_ListBucketRequest.Size(m)
}
func (m *ListBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketRequest proto.InternalMessageInfo

func (m *ListBucketRequest) GetOwnerID() int64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

func (m *ListBucketRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListBucketRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListBucketRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type ListBucketReply struct {
	Buckets              []*BucketInfo `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Total                int32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Status               int32         `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string        `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListBucketReply) Reset()         { *m = ListBucketReply{} }
func (m *ListBucketReply) String() string { return proto.CompactTextString(m) }
func (*ListBucketReply) ProtoMessage()    {}
func (*ListBucketReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{9}
}

func (m *ListBucketReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketReply.Unmarshal(m, b)
}
func (m *ListBucketReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketReply.Marshal(b, m, deterministic)
}
func (m *ListBucketReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketReply.Merge(m, src)
}
func (m *ListBucketReply) XXX_Size() int {
	return xxx_messageInfo_ListBucketReply.Size(m)
}
func (m *ListBucketReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketReply proto.InternalMessageInfo

func (m *ListBucketReply) GetBuckets() []*BucketInfo {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *ListBucketReply) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListBucketReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListBucketReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type BucketInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerID              int64    `protobuf:"varint,4,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6900a62be1fd2c, []int{10}
}

func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BucketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BucketInfo) GetOwnerID() int64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

func (m *BucketInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *BucketInfo) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateBucketRequest)(nil), "api.bucket.v1.CreateBucketRequest")
	proto.RegisterType((*CreateBucketReply)(nil), "api.bucket.v1.CreateBucketReply")
	proto.RegisterType((*UpdateBucketRequest)(nil), "api.bucket.v1.UpdateBucketRequest")
	proto.RegisterType((*UpdateBucketReply)(nil), "api.bucket.v1.UpdateBucketReply")
	proto.RegisterType((*DeleteBucketRequest)(nil), "api.bucket.v1.DeleteBucketRequest")
	proto.RegisterType((*DeleteBucketReply)(nil), "api.bucket.v1.DeleteBucketReply")
	proto.RegisterType((*GetBucketRequest)(nil), "api.bucket.v1.GetBucketRequest")
	proto.RegisterType((*GetBucketReply)(nil), "api.bucket.v1.GetBucketReply")
	proto.RegisterType((*ListBucketRequest)(nil), "api.bucket.v1.ListBucketRequest")
	proto.RegisterType((*ListBucketReply)(nil), "api.bucket.v1.ListBucketReply")
	proto.RegisterType((*BucketInfo)(nil), "api.bucket.v1.BucketInfo")
}

func init() {
	proto.RegisterFile("api/bucket/v1/bucket.proto", fileDescriptor_2c6900a62be1fd2c)
}

var fileDescriptor_2c6900a62be1fd2c = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x95, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0xc7, 0xe5, 0xa4, 0x69, 0xd7, 0xa7, 0xfb, 0xad, 0xab, 0xfb, 0x83, 0x85, 0x30, 0x58, 0x95,
	0x53, 0xd5, 0x43, 0xab, 0x6e, 0x37, 0x10, 0x07, 0xb6, 0x09, 0x54, 0x89, 0x03, 0x0a, 0xe2, 0xc2,
	0x65, 0x72, 0x1b, 0x53, 0x59, 0x6b, 0xe3, 0x90, 0xb8, 0x45, 0x1b, 0x20, 0x24, 0x0e, 0xbc, 0x01,
	0x4e, 0xbc, 0x03, 0xde, 0x0f, 0x12, 0x12, 0x77, 0x5e, 0x08, 0xb2, 0x93, 0x36, 0x7f, 0xd7, 0x09,
	0xc1, 0x01, 0x71, 0x8a, 0xfd, 0xf8, 0xb1, 0x3f, 0x5f, 0x3f, 0xb1, 0xbf, 0x06, 0x8b, 0xf8, 0x6c,
	0x30, 0x5e, 0x4c, 0xce, 0xa9, 0x18, 0x2c, 0x87, 0x71, 0xab, 0xef, 0x07, 0x5c, 0x70, 0xfc, 0x1f,
	0xf1, 0x59, 0x3f, 0x8e, 0x2c, 0x87, 0xd6, 0xfe, 0x94, 0xf3, 0xe9, 0x8c, 0x0e, 0xe4, 0x0c, 0xe2,
	0x79, 0x5c, 0x10, 0xc1, 0xb8, 0x17, 0x46, 0xc9, 0x36, 0x85, 0xf6, 0x49, 0x40, 0x89, 0xa0, 0xc7,
	0x6a, 0x82, 0x43, 0x5f, 0x2d, 0x68, 0x28, 0x30, 0x86, 0x8a, 0x47, 0xe6, 0xd4, 0x44, 0x1d, 0xd4,
	0xad, 0x3b, 0xaa, 0x8d, 0x3b, 0xd0, 0x70, 0x69, 0x38, 0x09, 0x98, 0x2f, 0x17, 0x30, 0x35, 0x35,
	0x94, 0x0e, 0x61, 0x13, 0x6a, 0xfc, 0xb5, 0x47, 0x83, 0xd1, 0xa9, 0xa9, 0x77, 0x50, 0x57, 0x77,
	0x56, 0x5d, 0xfb, 0x3b, 0x82, 0x56, 0x96, 0xe3, 0xcf, 0x2e, 0xf0, 0x0e, 0x68, 0xcc, 0x55, 0x0c,
	0xdd, 0xd1, 0x98, 0xbb, 0xa6, 0x6a, 0x57, 0x53, 0xf5, 0x8d, 0xd4, 0x4a, 0x86, 0x8a, 0xf7, 0xa1,
	0x3e, 0x51, 0x50, 0xf7, 0xa1, 0x30, 0x0d, 0x35, 0x96, 0x04, 0xe4, 0xe8, 0xc2, 0x77, 0xe3, 0xd1,
	0x6a, 0x34, 0xba, 0x0e, 0xe0, 0x9b, 0x50, 0x0d, 0x05, 0x11, 0x8b, 0xd0, 0xac, 0x75, 0x50, 0xd7,
	0x70, 0xe2, 0x1e, 0xde, 0x05, 0x7d, 0x1e, 0x4e, 0xcd, 0x2d, 0xa5, 0x43, 0x36, 0xed, 0xb7, 0xd0,
	0x7e, 0xae, 0xa6, 0x65, 0x4b, 0xf8, 0x67, 0x36, 0x77, 0x00, 0x0d, 0xee, 0xd3, 0x80, 0x08, 0x1e,
	0x9c, 0x31, 0x37, 0xde, 0x20, 0xac, 0x42, 0x23, 0xd7, 0x7e, 0x00, 0xad, 0x2c, 0x5d, 0x16, 0x36,
	0x11, 0x8f, 0xca, 0xc4, 0x6b, 0x89, 0xf8, 0x47, 0xd0, 0x3e, 0xa5, 0x33, 0x7a, 0x9d, 0xf8, 0x9c,
	0x0c, 0xad, 0x4c, 0x46, 0x76, 0x9d, 0x5f, 0x93, 0x71, 0x02, 0xbb, 0x8f, 0xa9, 0xf8, 0x4d, 0x0d,
	0xdf, 0x10, 0xec, 0xa4, 0x56, 0xf9, 0x77, 0x4e, 0xd8, 0x7b, 0x68, 0x3d, 0x61, 0x61, 0xae, 0x3c,
	0x29, 0x51, 0x28, 0x2b, 0x0a, 0x43, 0xc5, 0x27, 0xd3, 0x68, 0x93, 0x86, 0xa3, 0xda, 0xf8, 0x36,
	0xd4, 0xe5, 0xf7, 0x2c, 0x64, 0x97, 0x54, 0x6d, 0xd1, 0x70, 0xb6, 0x64, 0xe0, 0x19, 0xbb, 0xa4,
	0xd7, 0x1f, 0xb2, 0x8f, 0x08, 0x9a, 0x69, 0x05, 0xb2, 0xb4, 0x47, 0x50, 0x8b, 0x4c, 0x46, 0xfe,
	0x5d, 0xbd, 0xdb, 0x38, 0xbc, 0xd5, 0xcf, 0x18, 0x4f, 0x3f, 0x4a, 0x1e, 0x79, 0x2f, 0xb9, 0xb3,
	0xca, 0xc4, 0xff, 0x83, 0x21, 0xb8, 0x20, 0xb3, 0x58, 0x5b, 0xd4, 0x49, 0x55, 0xc2, 0x28, 0xab,
	0x44, 0x35, 0xa9, 0xc4, 0x17, 0x04, 0x90, 0xac, 0xfb, 0x37, 0xff, 0xde, 0xc3, 0xcf, 0x15, 0xa8,
	0x46, 0x52, 0xf1, 0x39, 0x6c, 0xa7, 0xcd, 0x0f, 0xdb, 0xb9, 0x4a, 0x95, 0x38, 0xb0, 0xd5, 0xd9,
	0x98, 0xe3, 0xcf, 0x2e, 0xec, 0x1b, 0x1f, 0xbe, 0xfe, 0xf8, 0xa4, 0x35, 0x6d, 0x48, 0x5e, 0x80,
	0x7b, 0xa8, 0x27, 0x61, 0x69, 0x43, 0x28, 0xc0, 0x4a, 0xbc, 0xaa, 0x00, 0x2b, 0x38, 0xca, 0x0a,
	0x66, 0x15, 0x61, 0xe9, 0x6b, 0x5f, 0x80, 0x95, 0x78, 0x4b, 0x01, 0x56, 0xf0, 0x8d, 0x15, 0xac,
	0x97, 0x83, 0xb9, 0x50, 0x5f, 0x5f, 0x6f, 0x7c, 0x90, 0x5b, 0x25, 0x6f, 0x1f, 0xd6, 0x9d, 0xab,
	0x13, 0x24, 0x63, 0x4f, 0x31, 0x5a, 0xb8, 0x99, 0x30, 0x06, 0x6f, 0x98, 0xfb, 0x0e, 0x8f, 0x01,
	0x92, 0xa3, 0x8e, 0xf3, 0x62, 0x0b, 0xf7, 0xd0, 0xba, 0xbb, 0x21, 0x43, 0x82, 0xb0, 0x02, 0x6d,
	0xe3, 0xd4, 0x66, 0x8e, 0x7b, 0x90, 0x7d, 0xa4, 0x9f, 0xa2, 0x17, 0x7b, 0x73, 0x12, 0x0a, 0x1a,
	0x0c, 0x32, 0x0f, 0xfb, 0xfd, 0xe5, 0x70, 0x5c, 0x55, 0x0f, 0xf5, 0xd1, 0xcf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x94, 0x81, 0xab, 0x66, 0xf3, 0x07, 0x00, 0x00,
}
